#!/bin/sh

plistFile="com.unnecessary-labs.mac.DQ.plist"
daemonDirPath="/Library/LaunchDaemons"

sudo cp -f $plistFile $daemonDirPath
sudo chmod 600 $daemonDirPath/$plistFile
sudo chown root $daemonDirPath/$plistFile
