theme: jekyll-theme-dinky
title: Digital Quarantine
description: An app that you can't quit
show_downloads: true
github:
  pkg_url: https://github.com/bharathbhargavgb/digital-quarantine/releases/download/v1.0/DigitalQuarantineInstaller.pkg
