theme: jekyll-theme-dinky
title: Digital Quarantine
description: An app that you can't easily quit
show_downloads: true
github:
  pkg_url: https://github.com/bharathbhargavgb/digital-quarantine/releases/download/v1.1/DigitalQuarantineInstaller.pkg
